export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';
export const GET_USER_FOLLOWERS_SUCCESS = 'GET_USER_FOLLOWERS_SUCCESS';
export const GET_USER_FOLLOWERS_FAILURE = 'GET_USER_FOLLOWERS_FAILURE';

export const GET_USER_REPOS = 'GET_USER_REPOS';
export const GET_USER_REPOS_SUCCESS = 'GET_USER_REPOS_SUCCESS';
export const GET_USER_REPOS_FAILURE = 'GET_USER_REPOS_FAILURE';

export const GET_USER_REPO_COMMITS = 'GET_USER_REPO_COMMITS';
export const GET_USER_REPO_COMMITS_SUCCESS = 'GET_USER_REPO_COMMITS_SUCCESS';
export const GET_USER_REPO_COMMITS_FAILURE = 'GET_USER_REPO_COMMITS_FAILURE';

export const GET_USER_CONTRIBUTION = 'GET_USER_CONTRIBUTION';
export const GET_USER_CONTRIBUTION_SUCCESS = 'GET_USER_CONTRIBUTION_SUCCESS';
export const GET_USER_CONTRIBUTION_FAILURE = 'GET_USER_CONTRIBUTION_FAILURE';